# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
name: c_project_template

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
    types: ready_for_review

jobs:
  format:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt install clang-format-18
      - run: make format_dry_run

  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - run: make
